
link : list item_str main concessionaria
	gcc list.o item_str.o main.o concessionaria.o -o esercizio2.exe

concessionaria :
	gcc -c concessionaria.c

item_str :
	gcc -c item_str.c

item_int :
	gcc -c item_int.c

list :
	gcc -c list.c

main : 
	gcc -c main.c

clean : 
	rm *.o *.exe

