link : main item list stack queue
	gcc main.o item.o list.o stack.o queue.o -o codastack

main :
	gcc -c main.c

item :
	gcc -c item_int.c -o item.o

list :
	gcc -c list.c

stack :
	gcc -c stack_list.c -o stack.o

queue :
	gcc -c queue-stack.c -o queue.o

clean :
	rm -f *.o codastack